apiVersion: apps/v1
kind: Deployment
metadata:
  name: oracle
  labels:
    app: oracle
spec:
  selector:
    matchLabels:
      app: oracle
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: oracle
    spec:
      containers:
        - image: quay.io/maksymbilenko/oracle-xe-11g
          name: oracle
          ports:
            - containerPort: 1521
              name: oracle
          volumeMounts:
            - name: oracle-init
              mountPath: /docker-entrypoint-initdb.d/init.sql
              subPath: init.sql
      volumes:
        - name: oracle-init
          configMap:
            name: oracle-init
            items:
              - key: init.sql
                path: init.sql
---

apiVersion: v1
kind: Service
metadata:
  name: oracle
  labels:
    app: oracle
spec:
  type: NodePort
  ports:
    - port: 1521
      nodePort: 31521
  selector:
    app: oracle
